# -*- coding: utf-8 -*-
"""Vizualipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PJeCE2SMJ2N97uB8EdIyw0DelxZzU3CV
"""

import matplotlib.pyplot as plt

arr = [2,10,20,30,20,40]
arr_x=[20,30,5,4,20,5]
plt.hist(arr);
# plt.show()

arr = [2,10,20,30,20,40]
arr_2=[5,20,10,20,30,50]
plt.plot(arr_2,label='fig1')
plt.plot(arr,label='fig2');

import numpy as np
import random

random_data=np.random.rand(100000)
random_data1=np.random.randint(1000)
plt.hist(random_data,bins=50);

values=[10,20,30,50]
labels= ['python','c++', 'java', 'c']
plt.pie(values,labels=labels, explode=[10,0,0,0])

import numpy as np
a = np.random.randn(100000, 7)

import seaborn as sns

sns.histplot(a)

fig, ax = plt.subplots(figsize=(10,7),nrows=2,ncols=2)

x=np.linspace(-10,10,100)
ax[0,0].plot(x,np.sin(x));
ax[0,1].pie(values,labels=labels,explode=[0,0,0.2,0])
ax[1,0].scatter(np.random.randn(1000),np.random.randn(1000));
ax[1,1].plot(x,np.sqrt(x));

plt.subplot(2,1,1)
plt.plot(x,np.sin(x));
plt.subplot(2,1,2)
plt.plot(x,np.cos(x));

random_data1=np.random.randn(1000)
plt.boxplot(random_data1);

import matplotlib.pyplot as plt

nums=[1,7,9,11,13,15,21,30,31]
plt.plot(nums)

x=[1,20,13,44,35]
y=[6,17,8,29,40]
plt.plot(x, label='first')
plt.plot(y,label='second');

fig,ax=plt.subplots(figsize=(10,7))
bar=ax.bar(x,y);
ax.set(title='first',xlabel='x',ylabel='y');
fig.savefig('fig.plot.png')

import numpy as np
import random

x=np.random.rand(100)

fig,ax=plt.subplots(figsize=(7,5))
bar=ax.bar(x,np.sqrt(x));
ax.set(title='sqrt value',xlabel='x value',ylabel='sqrt value');

y=np.linspace(0,10,100)
fig,ax=plt.subplots(figsize=(7,5))
plot=ax.plot(y,y**2);

fig,ax=plt.subplots(figsize=(7,5))
scatter=ax.scatter(y,np.exp(y))

fig,ax=plt.subplots(figsize=(7,5))
scatter=ax.scatter(y,np.sin(y))
ax.set(title='sin of y',xlabel='y',ylabel='sin(y)');

food={'apple':10,'stawberry':15,'cherry':5}
fig,ax=plt.subplots()
bar=ax.bar(food.keys(),food.values());
ax.set(title='foods payment',xlabel='food name',ylabel='payment');

food={'apple':10,'stawberry':15,'cherry':5}
fig,ax=plt.subplots()
barh=ax.barh(list(food.keys()),list(food.values()));
ax.set(title='foods payment',xlabel='food name',ylabel='payment');

x=np.random.randn(1000)
plt.hist(x);

X=np.random.rand(1000)
plt.hist(X);

fig,ax=plt.subplots(figsize=(10,7),nrows=2,ncols=2)
ax[0,0].plot(x,x/2);
ax[0,1].scatter(np.random.random(10),np.random.random(10),c='r');
ax[1,0].bar(food.keys(),food.values());
ax[1,1].hist(np.random.randn(1000));

import pandas as pd

!wget https://raw.githubusercontent.com/Rstam59/TaskDataRepoForStudents/refs/heads/main/car-sales.csv

df=pd.read_csv('car-sales.csv')
df

df['Price']=df['Price'].str.replace("[\$\.\,]","",regex=True)
df

df['Price'].astype(int).plot()

df['total sales']=df['Price'].astype(int).cumsum()
df

df['sales date']=pd.date_range("13/12/2024", periods=len(df))
df

fig,ax=plt.subplots(figsize=(7,5))
plot=ax.plot(df['total sales'],df['sales date']);

fig,ax=plt.subplots(figsize=(7,5))
scatter=ax.scatter(df['Odometer (KM)'],df['Price'].astype(int),c='r');

l=np.random.rand(10,4)
pd.DataFrame(l, columns= ['a','b','c','d',]).plot(kind='bar')

fig,ax=plt.subplots(figsize=(7,5))
bar=ax.bar(df['Make'],df['Odometer (KM)']);

df.plot(x="Make", y="Odometer (KM)", kind="bar")

df['Odometer (KM)'].plot(kind='hist');

df['Price'].astype(int).plot(kind='hist',bins=20)

!wget https://raw.githubusercontent.com/Rstam59/TaskDataRepoForStudents/refs/heads/main/heart-disease.csv

df1=pd.read_csv('heart-disease.csv')
df1

df1.head(10)

df1['age'].hist(bins=50)

df1.plot.hist(figsize=(10,30),subplots=True);

ages=df1[df1['age']>50]

fig,ax=plt.subplots(figsize=(7,5))
scatter=ax.scatter(ages['age'],ages['chol'],c=ages['target'])
ax.set(title='age and chol',xlabel='age',ylabel='chol')
ax.legend(*scatter.legend_elements())
ax.axhline(ages["chol"].mean(),
linestyle="--");

plt.style.available



plt.style.use('seaborn-v0_8-whitegrid')
fig,ax=plt.subplots(figsize=(7,5))
scatter=ax.scatter(ages['age'],ages['chol'],c=ages['target'],cmap='winter')
ax.set(title='age and chol',xlabel='age',ylabel='chol')
ax.legend(*scatter.legend_elements())
ax.axhline(ages["chol"].mean(),
linestyle="--",c='r');
fig.savefig('pict.saved.png')

